WT-12475 remove indexes tests and ex
wiredtiger/wiredtiger pull request #10893
Opened 2024-07-18 16:23 UTC by ruby-oujo

2024-07-18 16:40 UTC, ruby-oujo commented on test/evergreen.yml
> -    - name: linux-directio
This keeps slipping back into the changes, I think when merging develop this goes back in without merge conflicts :/

2024-07-18 23:15 UTC, ruby-oujo commented on examples/c/ex_col_store.c
Removing the usage of indexes affects most of this code; I spoke to @Sean04 about the effort to rewrite this and was probably not worth it.

2024-07-23 18:57 UTC, tod-johnson-mongodb commented on test/csuite/wt2909_checkpoint_integrity/main.c
> - * The data is stored in two tables, one having indices. Both tables have the same keys and are
Please rewrite to explain the two tables without mentioning indexes.

* The data is stored in two tables. Both tables have the same keys and are
* updated with the same key in a single transaction.
*

2024-07-23 23:28 UTC, tod-johnson-mongodb commented on test/suite/test_alter01.py
>          if self.use_cg:
New lines 126-128 can be changed to: cgparam = 'columns=(k,v),colgroups=(g0),"

2024-07-23 23:30 UTC, tod-johnson-mongodb commented on test/suite/test_alter01.py
> +                    special = self.use_cg
Delete new line 166.

2024-07-23 23:31 UTC, tod-johnson-mongodb commented on test/suite/test_alter01.py
>                      if not special:
Change to if not self.use_cg:

2024-07-23 23:32 UTC, tod-johnson-mongodb commented on test/suite/test_alter02.py
>              cgparam = 'columns=(k,v),'
Combine cgparam lines into one line.

2024-07-23 23:32 UTC, tod-johnson-mongodb commented on test/suite/test_alter02.py
> +        special = self.use_cg
Delete special and replace with self.use_cg

2024-07-23 23:33 UTC, tod-johnson-mongodb commented on test/suite/test_alter04.py
>              cgparam += 'colgroups=(g0),'
Combine cgparam lines into one line.

2024-07-23 23:33 UTC, tod-johnson-mongodb commented on test/suite/test_alter04.py
> +            special = self.use_cg
Delete special and replace with self.use_cg.

2024-07-23 23:36 UTC, tod-johnson-mongodb commented on test/suite/test_backup28.py
> -            self.session.checkpoint()
Why is old line 69 self.session.checkpoint() deleted?

2024-07-23 23:39 UTC, tod-johnson-mongodb commented on test/suite/test_cursor_bound01.py
>          if self.use_colgroup:
Combine create_params lines into one line.

2024-07-23 23:43 UTC, tod-johnson-mongodb commented on test/suite/test_cursor_compare.py
> -            self.assertRaisesWithMessage(
ix_0 always == None. Delete new lines 107-112 and new lines 74-77.

2024-07-23 23:45 UTC, tod-johnson-mongodb commented on test/suite/test_cursor_compare.py
> -            self.assertRaisesWithMessage(
ix0_0 always == None. Delete new lines 176-180 and 143-146.

2024-07-23 23:52 UTC, tod-johnson-mongodb commented on test/suite/test_metadata_cursor04.py
> +    # Test a complex table with column groups..
Change ".." to "."

2024-07-23 23:53 UTC, tod-johnson-mongodb commented on test/suite/test_pack.py
> -        forw.close()
Do not delete old line 77.

2024-07-24 00:00 UTC, tod-johnson-mongodb commented on tools/backup_analysis.py
> +    # For collections if logging is disabled, then it is replicated.
Change "they is replicated" to "they are replicated" since collections is plural.

2024-07-24 00:47 UTC, tod-johnson-mongodb requested changes
Some changes needed.
Also does not pass some tests.

2024-08-01 01:40 UTC, korteland commented
Closing this out as the project is on ice for Q3.

2024-08-01 01:40 UTC, closed without merging