WT-6912 Architecture Guide - logging page.
wiredtiger/wiredtiger pull request #6272
Opened 2021-02-01 20:03 UTC by sueloverso

This is ready for the first round of review.

2021-02-08 07:58 UTC, tammybailey requested changes

2021-02-08 07:58 UTC, tammybailey commented on src/docs/arch-logging.dox
> +* alloc_lsn: This is the LSN for the next log record allocation.
Capitalisation of "this" is inconsistent across the four items

2021-02-08 07:58 UTC, tammybailey commented on src/docs/arch-logging.dox
> +The third internal thread manages advancing the \c write_lsn in proper LSN order.
What does proper LSN order mean? I feel like the second sentence repeats what you said in the first. Would it make sense to rewrite as "The third internal thread manages advancing the `write_lsn`. As the `write_lsn` must be advanced in proper LSN order, it becomes a point of single threading in the path of writing a log record."

2021-02-08 07:58 UTC, tammybailey commented on src/docs/arch-logging.dox
> +that string into the write-ahead log as a message record type.
Does message record type mean `WT_LOGREC_MESSAGE`?

2021-02-08 07:58 UTC, tammybailey commented on src/docs/arch-logging.dox
> +# Remove this line and uncomment the next line after the rollback to stable page exists.
[This page exists](https://github.com/wiredtiger/wiredtiger/blob/develop/src/docs/arch-rts.dox).

2021-02-11 20:31 UTC, sueloverso commented on src/docs/arch-logging.dox
> +@subsection Log-related files in the database directory
Thanks fixed.

2021-02-11 20:41 UTC, sueloverso commented on src/docs/arch-logging.dox
> +There varying number of temporary and prepared log files in the directory. They
FYI, as I go through your comments, if I just accept it, I'm going to resolve it as I make my edit and not type "Fixed" into every single box. I'll only reply if I disagree for some reason.

2021-02-24 08:48 UTC, tammybailey approved these changes
One small punctuation comment, otherwise LGTM!

2021-02-24 08:48 UTC, tammybailey commented on src/docs/arch-logging.dox
> +Log archiving is disabled when a backup cursor is open, WiredTiger must guarantee
I think the `','` after `open` should be a `'.'`.

2021-02-24 16:03 UTC, merged