WT-7271 Coverity: Resource leak
wiredtiger/wiredtiger pull request #6370
Opened 2021-03-05 21:16 UTC by sueloverso

2021-03-05 21:52 UTC, keitharnoldsmith requested changes

2021-03-05 21:52 UTC, keitharnoldsmith commented on src/tiered/tiered_cursor.c
> +        __wt_free(session, cursor->uri);
I think this is going to be a problem.  In the normal case, where `wt_curtiered_close()` returns success, it will end by calling `wt_cursor_close()` which frees the cursor (and the uri).  So using `cursor` here will cause a use-after-free error.    

Coverity must think there is a path through `wt_curtiered_close()` where we terminate early and don't free the cursor and uri, but I'm not seeing it.

I looked briefly at the corresponding LSM cursor code, which this was copied from, and it's pretty similar. I'm not sure why Coverity doesn't complain about that as well.

2021-03-09 00:13 UTC, hbokhari commented
@sueloverso - I just dealt with similar looking Coverity reported bug (WT-7274) in history store cursor implementation. I concur with @keitharnoldsmith and believe this is a false positive. If you are eventually calling `__wt_curtiered_close()->__wt_close_cursor()` in the error handling case for the cursor open routine, we will never leak the memory pointed by `cursor->uri`.

2021-03-09 14:57 UTC, sueloverso commented
Thanks both of you! I have marked this a false positive in Coverity and will close the ticket and this PR.

2021-03-09 14:57 UTC, closed without merging