WT-6855 Initial implementation of runtime monitor
wiredtiger/wiredtiger pull request #6384
Opened 2021-03-15 05:29 UTC by luke-pearson

2021-03-15 06:17 UTC, etienneptl requested changes

2021-03-15 06:21 UTC, luke-pearson commented on dist/test_data.py
> +    Config('enabled', 'false', r'''
The thing is that these are subconfig statistics so its stat_cache_size=(enabled=,limit=) hence why I was using shorter words as their full definition is implied by context.

If we do stat_cache_size=(statistic_enabled=,limit_stat=) it seems very verbose.

2021-03-15 06:43 UTC, etienneptl commented on dist/test_data.py
> +    Config('limit', 0, r'''
As discussed, ok to leave it.

2021-03-15 06:43 UTC, etienneptl commented on dist/test_data.py
> +    Config('enabled', 'false', r'''
As discussed, ok to leave it.

2021-03-15 06:44 UTC, etienneptl commented on test/cppsuite/test_harness/api_const.h
> +static const char *ENABLED = "enabled";
As discussed, ok to leave it.

2021-03-15 06:44 UTC, etienneptl commented on test/cppsuite/test_harness/api_const.h
> +static const char *LIMIT = "limit";
As discussed, ok to leave it.

2021-03-15 06:45 UTC, etienneptl commented on test/cppsuite/test_harness/configuration.h
> +        if (nested->type != WT_CONFIG_ITEM::WT_CONFIG_ITEM_STRUCT)
If you decide to leave it as a pointer, please use testutil_assert instead of throwing an exception

2021-03-15 06:48 UTC, luke-pearson commented on test/cppsuite/test_harness/connection_manager.h
> +    create(std::string config, std::string home = DEFAULT_DIR)
Will leave default value for now.

2021-03-15 06:49 UTC, luke-pearson commented on test/cppsuite/test_harness/runtime_monitor.h
> +    bool _enabled = false;
`_enabled` is set in the constructor.

2021-03-15 06:52 UTC, luke-pearson commented on test/cppsuite/test_harness/runtime_monitor.h
> +        use_percent = ((cache_bytes_image + cache_bytes_other) / cache_bytes_max) * 100;
We need to retrieve 2 of the 3 every time, cache_bytes_max cannot be 0 so I can put an assertion there but it feels overkill.

2021-03-15 06:53 UTC, luke-pearson commented on test/cppsuite/test_harness/runtime_monitor.h
> +        testutil_check(session->open_cursor(session, STATISTICS_URI, nullptr, nullptr, &cursor));
I think we should just stick to the C++ version of it so its not ambiguous which one to use.

2021-03-15 06:54 UTC, luke-pearson commented on test/cppsuite/test_harness/runtime_monitor.h
> +            std::this_thread::sleep_for(std::chrono::milliseconds(1000 / _ops));
I don't think so as ops is an op/s value. So it needs to be 1000ms / op/s?

2021-03-15 07:22 UTC, etienneptl commented on test/cppsuite/test_harness/connection_manager.h
> +    create(const std::string config, const std::string home = DEFAULT_DIR)
const std::string **&**config, const std::string **&**home

2021-03-15 07:28 UTC, etienneptl commented on test/cppsuite/test_harness/runtime_monitor.h
> +    bool _enabled = false;
We need to discuss as I am missing something but if it is set in the constructor init list and wont change, you can declare it as
const bool _enabled;

2021-03-15 07:33 UTC, etienneptl commented on test/cppsuite/test_harness/runtime_monitor.h
> +        use_percent = ((cache_bytes_image + cache_bytes_other) / cache_bytes_max) * 100;
The one stat that does not change, should we retrieve it in the constructor or somewhere else only once ?

2021-03-15 07:35 UTC, etienneptl commented on test/cppsuite/test_harness/runtime_monitor.h
> +            std::this_thread::sleep_for(std::chrono::milliseconds(1000 / _ops));
It is correct, my bad

2021-03-16 00:35 UTC, etienneptl commented on test/cppsuite/test_harness/runtime_monitor.h
> +            testutil_assert(use_percent < limit);
Use testutil_die instead

2021-03-16 00:39 UTC, etienneptl commented on test/cppsuite/test_harness/runtime_monitor.h
> +            testutil_assert(use_percent < limit);
As discussed, testutil_assert is more verbose and better for us

2021-03-16 00:50 UTC, etienneptl approved these changes

2021-03-16 00:51 UTC, etienneptl commented
LGTM!

2021-03-16 00:52 UTC, merged