WT-7400 Set WT_CURSTD_HS_READ_ALL flag for the search before fixing the out of order timestamps
wiredtiger/wiredtiger pull request #6484
Opened 2021-04-26 00:24 UTC by mm-ng

2021-04-26 01:06 UTC, quchenhao commented on src/history/hs_rec.c
> +    if (ret == 0) {
The flag is set at the wrong place. It should be on the previous two search near `__wt_curhs_search_near_after`

2021-04-26 01:07 UTC, quchenhao requested changes
The flag should be set at the search near calls.

2021-04-26 23:36 UTC, quchenhao approved these changes

2021-04-26 23:40 UTC, quchenhao commented on src/history/hs_rec.c
> +    hs_read_all_flag = F_ISSET(hs_cursor, WT_CURSTD_HS_READ_ALL);
No need to set WT_CURSTD_HS_READ_COMMITTED flag if we set WT_CURSTD_HS_READ_ALL.

2021-04-26 23:41 UTC, quchenhao commented on src/history/hs_rec.c
> +    hs_read_all_flag = F_ISSET(hs_cursor, WT_CURSTD_HS_READ_ALL);
Can you run a mongodb patch build?

2021-04-26 23:42 UTC, quchenhao commented on src/history/hs_rec.c
> +
We need to clear the flag in err as well.

2021-04-27 12:11 UTC, kommiharibabu approved these changes
LGTM

2021-04-27 12:11 UTC, kommiharibabu commented on src/history/hs_rec.c
> +
No need for this new line.

2021-04-28 03:49 UTC, merged