Add arm64 implementation of rdtsc equivalent instruction
wiredtiger/wiredtiger pull request #6860
Opened 2021-08-03 16:36 UTC by AGSaidi

The instruction isn't exactly the same as instead of cpu cycles its a system
clock. However, this is the same clocksource used for clock_gettime() and
similar calls so it has the same true resolution as those.

2021-08-03 16:36 UTC, lukech commented
autobuild: Can one of the admins verify this patch?

2021-08-04 23:18 UTC, luke-pearson approved these changes
LGTM.

2021-08-05 00:00 UTC, luke-pearson requested changes
Hi @AGSaidi, would you be able to run the ./s_all script in dist/ as the patch build is failing with a spelling error and a clang format error.

2021-08-05 19:10 UTC, AGSaidi commented
@luke-pearson sorry about that, updated.

2021-08-06 00:43 UTC, luke-pearson commented
> luke-pearson sorry about that, updated.
No worries, thank you for submitted the PR! It's great to have additional support for different architectures.

2021-08-06 00:44 UTC, luke-pearson approved these changes
LGTM. @keithbostic please review.

2021-08-06 17:09 UTC, keithbostic approved these changes

2021-08-06 17:10 UTC, keithbostic commented
@AGSaidi, thank you!

@luke-pearson, I've merged.

2021-08-06 17:14 UTC, merged