WT-9477 Don't allow  checkpoint triggering internal page split which leads to corrupted internal page in the checkpoint
wiredtiger/wiredtiger pull request #8046
Opened 2022-06-19 23:52 UTC by quchenhao

2022-06-20 01:57 UTC, agorrod commented
We are going to hold off on this while we build a test program that exercises the code.

2022-06-21 23:31 UTC, agorrod requested changes
I have suggested an edit to the comment (thanks for adding one).

2022-06-21 23:58 UTC, quchenhao commented on src/btree/bt_split.c
> +     * referenced by two internal pages in the checkpoint.
[345c2e4](https://github.com/wiredtiger/wiredtiger/pull/8046/commits/345c2e4458a831dbc4c59569283d6580d9bbc2d7)

2022-06-22 00:03 UTC, agorrod approved these changes
LGTM if it passes testing.

2022-06-22 00:10 UTC, kommiharibabu approved these changes
LGTM

2022-06-22 03:38 UTC, merged