WT-9562 Move the new debug data members from WT_SESSION_IMPL to WT_CURSOR
wiredtiger/wiredtiger pull request #8119
Opened 2022-07-13 11:00 UTC by AlexeyAnisimovAU

This PR addresses the following comment in `wt-8372-format-mirror-objects` feature branch:  https://github.com/wiredtiger/wiredtiger/pull/7662#discussion_r916359214

2022-07-14 04:26 UTC, AlexeyAnisimovAU commented
It doesn't seem that the Evergreen fails are related to this change.

2022-07-17 22:43 UTC, agorrod commented on src/include/wiredtiger.in
> +	void *format_private_arg;
This is the change that makes using cursors unappealing. It's a change to the general public API of WiredTiger, even though it's undocumented. I'll think some more about whether the layering niceness warrants this intrusion into the public API.

2022-07-27 01:38 UTC, agorrod requested changes
I've thought about this, and I don't think the benefit justifies an API change here for now. I think we should *not* make this change.

Thanks for coding it up so we could see the consequence @AlexeyAnisimovAU

2022-07-27 01:41 UTC, AlexeyAnisimovAU commented
> I've thought about this, and I don't think the benefit justifies an API change here for now. I think we should _not_ make this change.
> 
> Thanks for coding it up so we could see the consequence @AlexeyAnisimovAU

Thank you for the review. I wasn't confident in the change either.

2022-07-27 01:41 UTC, closed without merging