WT-9228 Generate call log for rollback_transaction()
wiredtiger/wiredtiger pull request #8153
Opened 2022-07-27 04:55 UTC by Sean04

2022-07-27 23:16 UTC, Siddhartha8899 requested changes

2022-07-27 23:16 UTC, Siddhartha8899 commented on src/call_log/call_log.c
> +
`__call_log_print_input` here?

2022-07-28 01:11 UTC, Sean04 commented on src/call_log/call_log.c
> +
Fixed, thanks!

2022-07-28 03:43 UTC, Siddhartha8899 approved these changes

2022-07-28 05:04 UTC, merged