WT-11845 Fix transaction visibility issue with truncate
wiredtiger/wiredtiger pull request #9841
Opened 2023-11-08 03:30 UTC by jiechenbo

2023-11-08 05:30 UTC, kommiharibabu approved these changes
LGTM

2023-11-09 23:49 UTC, agorrod requested changes
Since we have understood the root cause of the failure, is it possible to create a more predictable reproducer?
I don't know if it is predictable enough that a Python reproducer can be constructed, if not the C++ test suite seems like a good candidate for a focused reproducer.

2023-11-10 06:27 UTC, jeremythorp commented
> Since we have understood the root cause of the failure, is it possible to create a more predictable reproducer? I don't know if it is predictable enough that a Python reproducer can be constructed, if not the C++ test suite seems like a good candidate for a focused reproducer.

I think we'll be able to create a simple, predictable reproducer, and @clarissecheah + @ajmorton are on the case!

2023-11-20 01:23 UTC, jeremythorp commented
> > Since we have understood the root cause of the failure, is it possible to create a more predictable reproducer? I don't know if it is predictable enough that a Python reproducer can be constructed, if not the C++ test suite seems like a good candidate for a focused reproducer.
> 
> I think we'll be able to create a simple, predictable reproducer, and @clarissecheah + @ajmorton are on the case!

@clarissecheah & @ajmorton have created a simple Python reproducer, which is awesome, and they have added it into this PR.

2023-11-21 04:42 UTC, agorrod reviewed
The fix here looks good to me, could you add some protection against re-introducing it to a dist script, something like would satisfy me even though I know it isn't very complete:

```
$ cat dist/s_visibility_checks 
#!/bin/bash

t=__wt.$$
trap 'rm -f $t' 0 1 2 3 13 15

cd ..

# Check to see if a time aggregate is used in a straight visibility check.
# It should never be - the "snap_min" visibility check should be used instead.
found=`grep -rnI "txn_visible.*addr.ta" src/`
if [ ! -z "$found" ]; then
	echo "Found invalid usage(s) of visibility check and a time aggregate window"
	echo "$found"
	exit 1
fi

exit 0
```

2023-11-21 21:38 UTC, jiechenbo commented
Great idea @agorrod , I added the script to the PR. I was thinking of improving the script but realised it is already quite simple and powerful, I can't find anything to improve, let me know what other great additions you were thinking of adding to the script.

2023-11-21 23:50 UTC, agorrod commented
> Great idea @agorrod , I added the script to the PR. I was thinking of improving the script but realised it is already quite simple and powerful, I can't find anything to improve, let me know what other great additions you were thinking of adding to the script.

I think making the script better involves making it significantly more sophisticated - parsing out all calls to the visibility functions and their parameters and then check to see whether the parameter is of the right type.
I tried extending the script to pull out the visibility function and a subsequent line (so it could catch split parameters most of the time), but even that got more complex and didn't yield immediate benefit.

I'd be happy for those extensions to be future work on the backlog (or not at all until they are needed).

2023-11-21 23:51 UTC, agorrod approved these changes
LGTM

2023-11-22 00:23 UTC, jeremythorp commented on src/btree/bt_delete.c
> + * age was marked deleted, a pointer to the WT_REF was saved in the deleting session's transaction
There's a small typo here: 'age' should be 'page'.

2023-11-22 00:24 UTC, jeremythorp commented on src/btree/bt_delete.c
> + * not visible to the transaction, page containing overflow items, pages containing prepared values,
'page' here probably should be 'pages'

2023-11-22 02:17 UTC, jeremythorp approved these changes
LGTM!

2023-11-22 21:56 UTC, jiechenbo commented
evergreen merge

2023-11-22 23:34 UTC, merged