WT-11062 Lock the page before checking time aggregate
wiredtiger/wiredtiger pull request #9893
Opened 2023-11-23 08:26 UTC by kommiharibabu

2023-11-24 01:57 UTC, kommiharibabu commented
@agorrod This is the lock change that I mentioned to protect against `ref->addr` being freed.

2023-11-26 20:50 UTC, ajmorton reviewed
One question about read/write vs spinlocks to start. Perf testing (linked on the Jira ticket) indicates things are ok but I'll investigate two outliers results to confirm .

2023-11-27 00:36 UTC, kommiharibabu commented on src/include/btmem.h
> +#define WT_PAGE_LOCK(s, p) __wt_spin_lock((s), &(p)->page_lock)
The macros here are mainly used to hide the internal locking logic. Suppose we want to change from spinlock to rwlock, we don't have to change the caller's code. Changing the code here is enough.

2023-11-27 01:15 UTC, kommiharibabu commented on src/include/btmem.h
> +    WT_SPINLOCK page_lock; /* Page's spinlock */
Yes, I agree that `btcur_skip_page` needs read access on the page. It has already taken an exclusive lock on the ref, so changing it to `rwlock` may not help as it does not allow two cursors to check on the same ref anyway. I don't see any advantage in changing it to `rwlock`.

2023-11-27 01:28 UTC, kommiharibabu commented on src/include/btree_inline.h
> +         * verify whether the page may be skipped or not.
Thanks, fixed.

2023-11-28 03:31 UTC, ajmorton commented on src/include/btmem.h
> +    WT_SPINLOCK page_lock; /* Page's spinlock */
Thanks! All makes sense. Happy to leave the lock as is.

2023-11-28 20:35 UTC, ajmorton approved these changes
LGTM, but I'd like to have a second pair of eyes on this before merging

2023-11-28 20:35 UTC, ajmorton commented on src/btree/bt_page.c
> +    ret = __wt_spin_init(session, &page->page_lock, "btree page");
Error handling in this function is now spread across two locations, but the existing error handling being inside a switch statement was already unusual. I'll spin up a neweng ticket to clean this up outside of the PR.

2023-12-07 22:43 UTC, agorrod requested changes
Hari and I talked about the change this morning. I don't love adding in a lock acquisition to tree traversal.

He is going to try moving to safe-free semantics for the WT_REF::addr field, similarly to how split-safe free works in conjunction with generation tracking.

2023-12-15 13:38 UTC, closed without merging